image: registry.gitlab.com/kitsudaiki/kitsunemimi-ci-docker-images/normal-tests:1.0.0

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo Working on branch $CI_COMMIT_REF_NAME
    - pwd
    - apt-get update
    - apt-get install -y libboost-filesystem-dev
    - ./build.sh test
    - mkdir upload
    - cp -r ../result/* upload/
    - cp ../build/libKitsunemimiConfig/tests/unit_tests/unit_tests upload/
    - cp ../build/libKitsunemimiConfig/tests/functional_tests/functional_tests upload/
  artifacts:
    paths:
      - upload
    expire_in: 1 week
  tags:
    - docker

unit_tests:
  stage: test
  script:
    - ls -l
    - apt-get update
    - apt-get install -y libboost-filesystem-dev
    - upload/unit_tests
  dependencies:
    - build
  tags:
    - docker

functional_tests:
  stage: test
  script:
    - ls -l
    - apt-get update
    - apt-get install -y libboost-filesystem-dev
    - upload/functional_tests
  dependencies:
    - build
  tags:
    - docker
