name: build-and-test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/kitsudaiki/kitsunemimi-ci-docker-images/normal-tests:1.2.0
    name: build-job
    steps:
      - name: "Checkout repository"
        run: |
          # use manually clone, because with the "actions/checkout@v3" action the name of the
          # branch can not be read by the git commands, which is necessary for the build-script
          git clone https://github.com/kitsudaiki/${GITHUB_REPOSITORY#*/}.git
          cd ${GITHUB_REPOSITORY#*/}
          git checkout ${GITHUB_REF#refs/heads/}
      - name: "Build project"
        run:  |
          cd ${GITHUB_REPOSITORY#*/}
          ./build.sh test
      - name: "Copy files"
        run: |
          mkdir /build_result
          cp -r result/* /build_result/
          ls build/${GITHUB_REPOSITORY#*/}/tests
          cp build/${GITHUB_REPOSITORY#*/}/tests/unit_tests/unit_tests /build_result/
          cp build/${GITHUB_REPOSITORY#*/}/tests/functional_tests/functional_tests /build_result/
      - name: "Check target-directory"
        run: ls -l /build_result
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: /build_result

  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/kitsudaiki/kitsunemimi-ci-docker-images/normal-tests:1.2.0
    name: unit-test-job
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Check directory"
        run: ls -l ./
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: result
          path: /build_result
      - name: "Check target-directory"
        run: ls -l /build_result
      - name: "Run test"
        run: |
          chmod +x /build_result/unit_tests
          /build_result/unit_tests

  functional_tests:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/kitsudaiki/kitsunemimi-ci-docker-images/normal-tests:1.2.0
    name: memory-leak-test-job
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Check directory"
        run: ls -l ./
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: result
          path: /build_result
      - name: "Check target-directory"
        run: ls -l /build_result
      - name: "Run test"
        run: |
          chmod +x /build_result/functional_tests
          /build_result/functional_tests

  cleanup:
    needs:  [unit_tests, functional_tests]
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/kitsudaiki/kitsunemimi-ci-docker-images/normal-tests:1.2.0
    name: cleanup-job
    steps:
      - name: "Delete artifacts"
        uses: geekyeggo/delete-artifact@v2
        with:
          name: result
